"""PROTOCOL.md specification generation (pipeline-spec 7)."""

from __future__ import annotations

from .models import FactsDoc

TYPE_LABELS = {
    "magic": "magic",
    "constant": "constant",
    "length": "length",
    "timestamp": "timestamp",
    "sequence": "sequence",
    "counter": "counter",
    "string": "string",
    "data": "data",
    "variable_tail": "variable payload",
}

FRAMING_LABELS = {
    "length_prefixed": "length-prefixed",
    "fixed_size": "fixed-size",
    "delimiter": "delimiter-terminated",
    "unknown": "undetermined",
}


def generate_protocol_md(doc: FactsDoc) -> str:
    """Deterministic markdown protocol specification (identical inputs, identical out)."""
    lines: list[str] = []
    proto_name = _proto_label(doc)
    lines.append(f"# {proto_name} protocol specification")
    lines.append("")
    lines.append(
        "*Generated by protodissect from a packet capture; every field below cites "
        "deterministic inference evidence.*"
    )
    lines.append("")

    capture = doc.session.capture
    lines.append("## Overview")
    lines.append("")
    ports = _ports(doc)
    transports = sorted({f.proto.upper() for f in doc.flows})
    framing = _framing_summary(doc)
    lines.append(f"- Transport: {', '.join(transports) or 'unknown'}")
    if ports:
        lines.append(f"- Ports: {ports}")
    lines.append(f"- Framing: {framing}")
    lines.append(f"- Message types: {len(doc.message_types)}")
    lines.append(f"- Source capture: `{capture.path}` (sha256 {capture.sha256[:16]}...)")
    lines.append(
        f"- {capture.packet_count} packets analyzed "
        f"({', '.join(doc.session.config.get('notes', [])) or 'no notes'})"
    )
    lines.append("")

    lines.append("## Field layout")
    lines.append("")
    for mt in doc.message_types:
        framing_label = FRAMING_LABELS.get(mt.framing, mt.framing)
        lines.append(f"### {mt.id} ({mt.dir}, {mt.count} messages, {framing_label})")
        lines.append("")
        if mt.length is not None:
            lines.append(f"Fixed message length: {mt.length} bytes.")
            lines.append("")
        lines.append("| offset | size | type | name | coverage |")
        lines.append("|---|---|---|---|---|")
        for f in mt.fields:
            label = TYPE_LABELS.get(f.type, f.type)
            name = f.name or f.id
            lines.append(f"| {f.offset} | {f.size} | {label} | `{name}` | {f.coverage:.2f} |")
        lines.append("")
        if mt.sample_hex:
            lines.append("Sample messages:")
            lines.append("")
            lines.append("```text")
            for hx in mt.sample_hex[:2]:
                lines.append(hx)
            lines.append("```")
            lines.append("")
        if mt.notes:
            for note in mt.notes:
                lines.append(f"> note: {note}")
            lines.append("")

    validation = doc.validation
    lines.append("## Validation")
    lines.append("")
    lines.append(
        f"- {validation.messages_parsed}/{validation.messages_total} messages "
        f"re-parse cleanly under this structure ({validation.parse_ratio:.1%})"
    )
    lines.append(
        f"- {validation.classified_bytes}/{validation.total_bytes} bytes are covered "
        f"by semantically classified fields ({validation.classified_ratio:.1%}); the "
        "rest is opaque data or variable payload"
    )
    lines.append("")

    if doc.naming and doc.naming.provider != "off":
        lines.append("## Field naming provenance")
        lines.append("")
        lines.append(
            f"- Named by {doc.naming.provider} ({doc.naming.model}), prompt "
            f"{doc.naming.prompt_version}; {doc.naming.dropped} proposal(s) dropped by "
            "validation"
        )
        lines.append("")
        lines.append(
            "Names are hypotheses validated against the capture; the deterministic "
            "default names (u16b_06 style) are always available in facts.json."
        )
        lines.append("")

    lines.append("## Evidence appendix")
    lines.append("")
    for mt in doc.message_types:
        lines.append(f"### {mt.id}")
        lines.append("")
        lines.append("| field | offset | rules |")
        lines.append("|---|---|---|")
        for f in mt.fields:
            rules = "; ".join(f.evidence) or "-"
            lines.append(f"| `{f.id}` | {f.offset} | {rules} |")
        lines.append("")
    return "\n".join(lines)


def _proto_label(doc: FactsDoc) -> str:
    name = doc.session.config.get("protocol_name", "unknown")
    return str(name).replace("-", " ").title() if name != "unknown" else "Unknown"


def _ports(doc: FactsDoc) -> str:
    ports = set()
    for f in doc.flows:
        for ep in (f.client, f.server):
            port = ep.rsplit(":", 1)[-1]
            if port.isdigit() and int(port) < 1024:
                ports.add(port)
    return ", ".join(sorted(ports))


FRAMING_LABELS = {
    "length_prefixed": "length-prefixed",
    "fixed_size": "fixed-size",
    "delimiter": "delimiter-terminated",
    "unknown": "undetermined",
}


def _framing_summary(doc: FactsDoc) -> str:
    kinds = [mt.framing for mt in doc.message_types]
    if not kinds:
        return "unknown"
    counts: dict[str, int] = {}
    for k in kinds:
        counts[k] = counts.get(k, 0) + 1
    best = max(counts, key=lambda k: counts[k])
    label = FRAMING_LABELS.get(best, best)
    mixed = [k for k in counts if k != best]
    if mixed:
        return (
            f"{label} (mixed: " + ", ".join(FRAMING_LABELS.get(k, k) for k in sorted(mixed)) + ")"
        )
    return label
